baseurl = "https://mostlyharmlessrunning.com/"
languageCode = "en-us"
title = "Mostly Harmless Running"
theme = "castanet"
googleAnalytics = ""
themesdir = "../.."
paginate = "5"
buildFuture = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[permalinks]
	# page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"


# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
[[Menu.Main]]
    name = "About"
    identifier = "about"
    url = "/about"

[[Menu.Main]]
    name = "Contact"
    identifier = "contact"
    url = "/contact"

[[Menu.Main]]
    name = "Hosts"
    identifier = "hosts"
    url = "/host"

[[Menu.Main]]
    name = "Guests"
    identifier = "guests"
    url = "/guest"

#[[Menu.Main]]
#    name = "Upcoming Episodes"
#    identifier = "upcoming"
#    url = "/upcoming"

#[[Menu.Main]]
#    name = "Books"
#    identifier = "books"
#    url = "/books"
#    parent = "resources"
#[[Menu.Main]]
#    name = "Podcasts"
#    identifier = "podcasts"
#    url = "/books"
#    parent = "resources"

[params]
mainSections = ["episode"]
episode_number_style  = "brackets"
episode_number_prefix = "CWC"
site_theme = "grey"
# site_layout = "grid"
site_layout = "row"
show_next_upcoming = "true"
enable_jumbo = "true"
# enable_jumbo = "false"
# truncate = "100"
about_logo = "/img/mostly.png"
favicon = "/icon/favicon-32x32.png"
copyright_notice = "Copyright 2021 [Mostly Harmless Running](https://github.com/therandomsecurityguy/mostlyharmless)"
itunes_subscribe = "https://podcasts.apple.com/us/podcast/mostly-harmless-running/id1452070673&ls=1"
android_subscribe = "https://www.google.com/podcasts?feed=aHR0cHM6Ly9mZWVkLnBvZGJlYW4uY29tL3Byb3Jlci9mZWVkLnhtbA%3D%3D"
spotify_subscribe = "https://open.spotify.com/show/..."
# rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
description = "This podcast features candid conversations with everyday runners. We share stories about our training, races, what we eat and the wild and ridiculous things that happen to us through it all. We keep it mostly harmless."
media_prefix = "https://f000.backblazeb2.com/file/mostlyharmless/"
disqusShortname = ""
  [params.feed]
    copyright = "Copyright 2021 Mostly Harmless Running" #do not use markdown in this field; it is used in the feed
    itunes_subtitle = "The best running podcast ever...well...maybe one of the best" #no markdown or HTML
    itunes_author = "Mostly Harmless Running" #no markdown or HTML
    itunes_summary = "This podcast features candid conversations with everyday runners. We share stories about our training, races, what we eat and the wild and ridiculous things that happen to us through it all. We keep it mostly harmless."
    itunes_owner_name = "Mostly Harmless Running"
    itunes_owner_email = "mostlyharmlessrunning@gmail.com" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on Apple Podcasts. It will not be publicly displayed on Apple Podcasts.
    itunes_image = "https://raw.githubusercontent.com/therandomsecurityguy/mostlyharmless/main/static/img/mostly.png" #fqdn to the image art for your podcast
    itunes_top_category = "Health & Fitness"
    itunes_first_sub_category = "Fitness"
    language = "en-us"

  [params.realfavicongenerator] # https://realfavicongenerator.net/
    mask_icon_color="#5bbad5"
    msapplication_tilecolor="#2b5797"
    theme_color="#ffffff"

  [params.podlove] # https://subscribe-button.podlove.org
    subscribe_title = ""              # fallback: site title from above
    subscribe_subtitle = ""           # fallback: ""
    subscribe_description = ""        # fallback: ""
    subscribe_cover = "img/logo.jpg"  # fallback: ""
    subscribe_color = "#585e6c"       # fallback: ""
    subscribe_size = "medium"         # options: small, medium, big
    subscribe_format = "rectangle"    # options: rectangle, square, cover
    subscribe_style = "filled"        # options: filled, outline, frameless
    subscribe_language = "en"         # options: nl (dutch), en (english), eo (esperanto), de (german), fi (finnish), fr (french), ja (french)
    subscribe_feed_type = "audio"     # options: audio, video
    subscribe_feed_format = "mp3"     # options: mp3, aac, ogg, opus

  [params.social]
    github = "therandomsecurityguy"
    instagram = "mostly_harmless_running"

  [params.authors]
    [params.authors.Matt]
      name	= "Happy Matt"
      thumbnail = "img/host/matt.png"
      bio = ""
      [params.authors.Matt.social]
        instagram = "mk_runs"
    [params.authors.Alyssa]
			name = "Alyssa"
			thumbnail = ""
			bio = ""
				[params.authors.Alyssa.social]
					instagram = "alfeuerer"
    [params.authors.Katie]
      name = "Katie"
      thumbnail = ""
      bio = ""
      [params.authors.Katie.social]
        instagram = "katie_walnuts"

    [params.links]
      [params.links.store]
        name = "Team Store"
        url = "https://pr-or-er.com/"
#      [params.links.ffs]
#        name = "Food Fight Show"
#        url = "https://foodfightshow.org"
#      [params.links.sdt]
#        name = "Software Defined Talk"
#        url = "https://cote.io/podcasts/sdt/"
